export * from "@/pages/dashboard/home";
export * from "@/pages/dashboard/profile";
export * from "@/pages/dashboard/tables";
export * from "@/pages/dashboard/notifications";
export * from "@/pages/dashboard/chat"
export * from "@/pages/dashboard/users"
export * from '@/pages/dashboard/expert'
export * from '@/pages/dashboard/garge'
export * from '@/pages/dashboard/fraud'
